### ISSUE TITLE
Problem with undo functionality

### ISSUE THREAD

**Issue by onlymx13** [MaxBittker/sandspiel#55] opened 2019-02-17 17:03 UTC
Place a layer of dust, then a layer of lava. The dust will obviously ignite. Now undo placing the lava. The dust will still ignite.

**Comment by MaxBittker** [comment] 2019-02-18 21:01
I was able to reproduce this - i try to avoid this by clearing out fluid state after undo, but I think it's no working because the fluid state is being reset either one frame too late, or because it's being reset incorrectly

Thanks for the issue

**Comment by MaxBittker** [comment] 2019-04-08 17:29
I have a fix for this locally that i'm going to merge as part of an upcoming UI re-write

**Closed by MaxBittker** 2019-04-08 17:29 UTC
